### ISSUE TITLE
Backup/Restore & Distribution in F-Droid

### ISSUE THREAD

**Issue by igoralmeida** [ltGuillaume/DroidShows#1]
Hi,

I'm a long-time DroidSeries user and was very happy to see somebody else taking up the development. I wanted to add some notifications, for example, but never mustered the courage to revive the project. Props.

I have not yet taken a look at your (new?) dependencies, but have you considered submitting the app to F-Droid? It should be quite straightforward if you don't require anything proprietary. I'd be happy to help.

**Comment by ltGuillaume** [comment]
Hi Igor,

Thanks for dropping me a note, appreciate it! Actually, since last week
I've been looking into things in order to put it on F-Droid! There are two
complications that need some extra work or research before I can do that:

   1. F-Droid requires, even for forks, that you have a unique package name
   for your project. Right now, it's still *org.droidseries*, so it's not
   fit for inclusion on F-Droid yet. Because of this, I'll also need to
   implement an import/export feature before switching to the new package
   name. Otherwise, current users will have to add their data all over again.
   2. I need to choose a proper license. Of course DroidSeries had its own
   license and it goes without saying that I intend to fully respect it, but I
   don't know much about the differences just yet and it might be a good idea
   to switch to another version of the license, for instance, if that is
   possible. As said, I don't know much about that stuff, so I'm gonna need to
   dive into the license mess before I make a decision and before DroidSeries
   (maybe I'll rename it to DroidShows then, but I think I read that the
   current license doesn't permit that) is fit for F-Droid distribution.

If you can shed some light on the above, it'd make me a happy man :P

Cheers!

Guillaume

**Comment by ltGuillaume** [comment]
What I've seen so far, it's easy to do with gradle, but I hate that stuff AND I've been using Eclipse instead of Android Studio, because in my experience it's still a lot easier on the hardware (and I am - believe it or not - programming on a 2005 laptop - with only my 5,5 yr old HTC Desire to test stuff on :P

As for what I use for debugging the database: common sense and http://sqlitebrowser.org ;)

Yeah just checked, original has GPLv3 already, so seems alright. Thanks for checking man :)

**Comment by igoralmeida** [comment]
Maybe we should split this into other issues blocking this one? One is refactoring the codebase to get a unique app, and other is the import/export feature.

I've been able to copy DroidSeries' sqlite file from /data/data/ and inspect it, but that's quite an undertaking for general users. This has implications for achieving a seamless transition.

**Comment by ltGuillaume** [comment]
I just added a primitive backup/restore function (in Options). Hope it
works in all other Android versions, too. You can help me out by checking
if it works properly and by sending logcats if it doesn't :)

**Comment by ltGuillaume** [comment]
...and here's the rebranded DroidShows: https://github.com/ltGuillaume/DroidSeries/tree/droidshows/

**Comment by ltGuillaume** [comment]
@igoralmeida I made the F-Droid submission here: https://f-droid.org/forums/topic/droidshows/

**Comment by igoralmeida** [comment]
Hey Guillaume,

I just installed the DroidSeries-4.12 version, did a backup and restored in DroidShows. Everything worked fine, except for a minor nuisance: a few of my series show up with a <?> unicode symbol after the name.

While this was already happening with 4.08, I can reproduce with a clean DroidShows as well. I'll create a new issue.
