### ISSUE TITLE
no shows listed after upgrade to cyanogenmod 13 and backup from oandbackup

### ISSUE THREAD

**Issue by leaf-node** [ltguillaume/droidshows#10]
i upgraded to cyanogenmod 13 and tried to restore the application data from oandbackup, however droidshows did not list any shows. backing up and restoring the apparently empty database did not fix the issue.

the good news is that i copied the database that oandbackup had in a zip file into /sdcard/ then attempted to restore from that database using the in-app restore button. i now have access to the database. let me know if you want me to upload the original database somewhere so you can take a peek.

thanks for the great app! : )

**Comment by ltguillaume** [comment]
So, restoring the the database from within oandbackup resulted in an empty list, while using DroidShows' own restore with the SAME DroidShows.db resulted in a proper restoration? The only difference would then be that DroidShows would update all shows directly after restoring. Did you restore the same DroidShows version you ran before upgrading, together with the data, both using oandbackup, or did you install a newer version of DroidShows before restoring the data from oandbackup? If the latter is the case, then one of the intermediate updates could have caused this and yes, I'd like to find out what's going on then. If so, what was the DroidShows version you backed up with oandbackup? You can upload the database [link removed] and I'll investigate. Thanks for reporting!

**Comment by leaf-node** [comment]
> So, restoring the the database from within oandbackup resulted in an empty list, while using DroidShows' own restore with the SAME DroidShows.db resulted in a proper restoration?

Correct.

I installed the original .apk and i tried equal to the prior and newer versions from f-droid. none of these versions recognized the db.

the version of droidshows i had originally installed was 6.3.

**Comment by ltguillaume** [comment]
I just copied over all the files from the backup to /data/nl.asymmetrics.droidshows and fixed the owner/permissions. Everything went fine. I even installed the APK from the backup, no issues. So finally I even installed oandbackup and restored your backup 1-on-1. No issues.

Sorry, can't see anything wrong with it. Maybe it's because there's still a db-journal in your backup? You could try and remove that file from the backup and try again, but I reckon you've already had some new entries in the now working database, so only do it if you wanna have the extra work to get to the bottom of it ;) Either way, it looks like a minor issue under very specific circumstances and DroidShows' own backup/restore routine seems to work just fine.
