### ISSUE TITLE
export human readable

### ISSUE THREAD

**Issue by nutpantz** [ltGuillaume/DroidShows#105]
It would be great to have an export of shows in human readable format.
I have no idea what the backup is like, if there is a way to view it if it's a common database file.

**Comment by casperklein** [comment]
If I remember correctly, it's a SQLite DB. If you are on windows for example, you can use [SQLite Studio](https://sqlitestudio.pl/) to open the DB backup.

**Comment by ltguillaume** [comment]
@nutpantz What do you consider "human readble"? Is comma separated values (CSV) human readable? Or some sort of JSON or (YA)ML idea? Or a HTML report kinda thing, ready for print? And what should be included and what should be discarded? There's a lot of variables here, all depending on what you'd eventually like to do with it. I probably won't do this, unless you have a specific goal in mind and you can convince me it's necessary 😛

**Comment by nutpantz** [comment]
I would say csv, title, how many seasons there are ,full seasons watched, and last episode seen so something like the Simpsons,25, S01-S15, S16E08 

Honestly i have about 100 shows on my droid shows and i shutter to think of the day it stops working, but i also want to mitigate to something that also has my library like Eric's movie database (which sucks for tv shows sadly when you have a big library to import) on the PC.   
Really i wish that phone apps like yours had desktop companions or compatiblity.
(Erics movie database has great file import from csv)
So really it's what you think has value for your project and what you find interesting.

I'm throwing out ideas that i would use. And hopefully learning

**Comment by ltguillaume** [comment]
I think the amount of info anyone would like to have exported from the database would vary greatly, so that would mean only a whole interface to export data to CSV would make sense. That isn't something I would want to create, simply because it's very easy to export from an SQLite database with other tools.

For instance, you can load a backup into any [SQLite editor](https://sqlitebrowser.org), then execute the following SQL statement:
```
Create VIEW "Overview" AS SELECT
	"serieName",
	"seasonCount",
	replace(replace("nextEpisode", "[ne] ", ""), "[on]", "on")
FROM series
```

This will create a new view, which can be exported to a CSV file.
