### ISSUE TITLE
Info via rottentomatoes

### ISSUE THREAD

**Issue by anaknaga** [ltguillaume/droidshows#22]
Thanks for your work on DroidShows, I'm really liking it!

This is more of a feature request. Would it be possible to add info via rottentomatoes below the IMDB one? I find it more reliable. Thanks again.

**Comment by ltguillaume** [comment]
​Thanks for the compliment, glad you like it!

I have no plans for adding support for RottenTomatoes, Trakt.tv or any
other online service, because that would mean I'd have to create a
second/third parsing system to hook into those APIs, just for a couple of
additional bits of information.

What I could do is add a context menu item to RottenTomatoes in the
External Resources. It would, however, only open up the search page, e.g.
https://www.rottentomatoes.com/search/?search=travelers and not go to the
show's page directly. I don't know if that would help you in any way?
