### ISSUE TITLE
Feature Request: Air time

### ISSUE THREAD

**Issue by C0rrupted0mn1p0tence** [ltguillaume/droidshows#33]
Love Droidshows. Excellent work!

I think a useful feature other users would enjoy is to have the air time come up with the air date as well.

Currently a user can press the IMDb link which will bring them to the website and show when the next air date and time is on TV. I'd love to see the new episode air time but not the next time it's on TV (because I watch a new show the hour after it airs to cut the commercials as I'm sure many do). Might be useful to have a toggle setting for those who do want both though.

**Comment by ltguillaume** [comment]
Hi! Thanks for your msg! I'm not exactly sure I get what you're asking for.
So you'd like to see the air time in the shows overview _instead of_ the
next air date? But that would mean you'd need to know the day o/t week the
show airs by heart, instead of the air time... Don't think that'll help
much.

You're saying that you need to go to IMDb to find the air time, but that's
not true: just long-press the poster of the show and you'll see the air
time. Does that help? If not, how would you like to see it exactly?

**Comment by C0rrupted0mn1p0tence** [comment]
Thanks! I completely forgot the long-press feature on the posters!

I would recommend reversing the long/short press info though. Or, combine the two. Most users I imagine short press first (and don't necessarily check the "readme/options" where it tells you the long press feature). You can still access the episode info after going through the season lists/full episode guide (which was very intuitive) but you can't access the show info any other way than the long press. 

I'd mark this as closed. :)

**Comment by ltguillaume** [comment]
We've had a discussion on the XDA forums, I believe, on what action to link to what "gesture" (long-press vs. tap vs. double tap) and concluded that normally the show details would be accessed less often than the next episode details. Hence, long-press lets you head to show details.

People who don't read the readme.md / website / information in options are lazy, and I can't help them. Plus, I think these "gestures" are rather hacky anyway, so most users will either navigate through the app or use the context menu that pops up when long-pressing a show title anyway.
