### ISSUE TITLE
Question/Feature Suggestion... 

### ISSUE THREAD

**Issue by Ibuprophen** [ltguillaume/droidshows#34]
I'm not sure if this can be done fairly easily or (i believe) it may possibly require much more work with the Coding...

Say that one (or more) episode(s) for any given show had already been previously populated with all the episode information and an update is performed (whether or not the "Current Season" is selected in the options) and the tvdb has, somehow, gone wacky with the information with nothing there or similar, it seems to me that the information will be removed due to the shows information on thetvdb being zero (please correct me if I'm wrong).

With that stated, If the information is zero, that once had been populated, would it be possible to be able to keep, revert, etc... the information that was once there?

Whereas the app identifying this and only updating an already populated field without just deleting the information all together?

I hope i had explained this okay via text but, if you would like me to elaborate on one or more areas, I'll be more than happy to...

Thanks a Bunch!!!

**Comment by ltguillaume** [comment]
Yeah I get what you mean. Unfortunately, as you said, it is quite a bit of work to change the update process. Since updating SQL rows is very expensive, and some benchmarking showed me that I might as well just remove al episodes from the database and then re-add them when updating, this is how it's currently implemented. It's not pretty under the hood, but it caused a really big performance boost. I have seen it happen just one time (data being removed from TheTVDB). Usually, that's only for a couple minutes, as someone is updating it in a completely stupid way. If you happen to be updating in those couple of minutes, you're just really unlucky. But seriously, you shouldn't be updating more than once a week anyway, it's no use.

It's just one of the disadvantages of relying on a community project. We'll have to learn to live with it.

**Comment by Ibuprophen** [comment]
Thank you very much for your time in explaining this. I wasn't aware of how this would create such an in depth modification to the whole app. One of the best things regarding this app is its simplicity without all the "Bling" the others (I've seen so far) has. Simple and to the point!
