### ISSUE TITLE
Context menu opens mostly below visible area

### ISSUE THREAD

**Issue by casperklein** [ltguillaume/droidshows#35]
That is how it looks like when I long tab "12 Monkeys" to open the context menu:

![screenshot_20170821-212511](https://user-images.githubusercontent.com/590174/29538024-3b0aac3e-86c4-11e7-9e1b-d00fba5f4f14.png)

**Comment by ltguillaume** [comment]
Wow, that's odd. I'm simply using the default context menu for Android. Have you updated to a new Android version or another custom ROM? Or does this behavior occur since a new version of DroidShows? Could you perhaps try a previous version of DroidShows and see if the problem persists?

**Comment by casperklein** [comment]
Android 7 (Stock ROM) @ Samsung S7

To be honest, I cannot say if this is a new issue or not. For testing I went back to 7.1.0 and the issue is at least already in that version.

**Comment by ltguillaume** [comment]
I'll check if someone else on Android 7 has the same issues. So far, I've
not been able to reproduce it.

**Comment by ltguillaume** [comment]
I just reproduced it in a new virtual machine. Android's behavior (probably from v7 on) is absurd and utterly stupid: if you long-press an item at the top of the list, it'll only allow the popup to have the size of less than 3 items, whereas for items further down the list, their context menus have increasingly more vertical space available on the screen. This makes no sense at all and is a serious bug in Android. Not sure how to circumvent this behavior without too much rewriting, because I can't find a thing about this issue online. Perhaps you can help me along? Maybe I'm just using the wrong search terms...

**Comment by Ibuprophen** [comment]
I had tested this out with 2 of my devices. I Has Android 6 and the other has Android 7.

I also had added that specific show to test this out on to see if it was specific to that show. 

The attached images are labeled accordingly to 3 different actions performed. 

![long-press-image](https://user-images.githubusercontent.com/18060271/29580326-285ae832-8765-11e7-84b1-b84e528e560c.jpg)
![double-tap-image](https://user-images.githubusercontent.com/18060271/29580332-30f7b4ca-8765-11e7-90ac-fa8261133fc1.jpg)
![long-press-information](https://user-images.githubusercontent.com/18060271/29580343-3ea66b98-8765-11e7-8015-c7e09f5d53da.jpg)

As you can see that I could not duplicate the issue. 

You can try just reinstalling the app over the installed one to see if that helps. 

If it IS still there, then the  only advice that I could give to casperklein is as follows:

1) Backup the DroidShows folder located in "/storage/emulated/0/DroidShows". 
2) Uninstall the DroidShows App and reboot. 
3) Reinstall the DroidShows app. 
4) Open the app and add the show back in. 
5) Try and see if the problem is is still there. 

If the problem IS still there. Go to the backup of the DroidShows folder, zip it up, then upload it here. 

If the problem IS NOT still there, then all i can state is that sometimes certain database type apps may experience (what I call) a little hiccup somehow and if it doesn't persist again then it may have been a 1 time fluky. 

I wish you the best of luck!

**Comment by ltguillaume** [comment]
In most cases, that is indeed the way to rule out any specific issue with your installation of the app or user data specifics. If you have the time, please do follow ibuprophen's steps, just to be sure. However, I think this is something specific to a bug in one Android version.

@ibuprophen1 I take it you long-pressed 12 Monkeys in that screenshot? So you don't have the issue. Neither has someone on Android 7 on an Xperia A1. As said, I _was_ able to reproduce the issue in a virtual machine by long-pressing a show and saw the height of the context menu increase with every next show in the list. @Casperklein could you tell me the exact Android version?

**Comment by ltguillaume** [comment]
I think I found a solution (well, workaround) for this OS-based issue. Stand by for a test version.

**Comment by ltguillaume** [comment]
@casperklein 
Please try [DroidShows_7.5.2TEST.zip](https://github.com/ltGuillaume/DroidShows/files/1243103/DroidShows_7.5.2TEST.zip).

Sources:
https://stackoverflow.com/questions/40867621/contextmenu-position-is-messed-up-in-android-7
https://www.mysysadmintips.com/other/programming/758-listview-pop-up-context-menu-broken-in-android-7-api-24
https://issuetracker.google.com/issues/37118658
https://github.com/k9mail/k-9/issues/1581

**Comment by casperklein** [comment]
I just installed the test build and the issue is gone 👍 Thank you for that really fast fix!!

For the record:

![screenshot_20170822-230724](https://user-images.githubusercontent.com/590174/29587609-c1a79e94-878e-11e7-8007-5975dc41c7c1.png)

**Comment by ltguillaume** [comment]
Thanks for the feedback, I'll formally issue v7.5.2 (no need to update, it's the same as the APK published here).
