### ISSUE TITLE
Feature request: Change autobackup location

### ISSUE THREAD

**Issue by fabiom** [ltguillaume/droidshows#47]
Hi,

I suggest the ability to change the frequency of the autobackup (from daily to every 3 days / weekly / every 2 weeks) and to choose the folder of the autobackup (I would like to choose my sync folder so I have my backups safe).

Thanks!

**Comment by Ibuprophen** [comment]
There's already the ability to choose an alternative backup and restore location but, there's an issue with permissions to backing up to an external MicroSD (even with all the permissions allowed in the System Apps location). 

Though the ease of noticing that feature may not be easily realized for some... 

If you, fabio-m, would like a little help with locating this, i can submit a few screenshots but, when you select the Backup/Restore option, just select the 3 dots "..." in the popup window.

**Comment by ltguillaume** [comment]
- I've got stuff in place to permanently change the backup folder, but as @ibuprophen1 said, there's new stuff in newer Android versions for permissions to write to SD cards and I'm gonna have to implement that. Although I understand the why, its implementation is annoying and stupid and will cost me some work and testing, so stay tuned. 
- I won't change the daily backup: it doesn't create a new backup if no changes were made since the last backup anyway. Furthermore, if you have an older backup, you'd have to backtrack in your mind of what could not have been checked as seen yet upon restore, just annoying.

@ibuprophen1 He already found it if he's talking about the auto-backup feature

**Comment by fabiom** [comment]
@ibuprophen1 Yes, I'm talking about the folder of the auto-backup.

@ltGuillaume 
>  it doesn't create a new backup if no changes were made since the last backup anyway.

Oh that's nice, I didn't realize that. I agree and will remove from the title.

Thanks for the reply, I'll stay tuned.

**Comment by Ibuprophen** [comment]
@fabio-m , Ahhh... I see the light now 👍 

The auto backup feature doesn't follow the same custom backup location when the manual backup directory has been selected.

I didn't realize this at all... Good catch! :1st_place_medal:  

@ltGuillaume , thank you for following up on both @fabio-m and my inquiry, :1st_place_medal:

**Comment by ltguillaume** [comment]
Making a backup will allow you to change the location of the daily backups to that folder.
[DroidShows_7.7.4.zip](https://github.com/ltGuillaume/DroidShows/files/1881195/DroidShows_7.7.4.zip)
Not sure if I'm gonna go through the hassle of allowing backups to an external SD card yet.
@fabio-m @ibuprophen1

**Comment by Ibuprophen** [comment]
@ltGuillaume, I tried updating the app first (to v7.7.4) and then a clean install with failed results for the External MicroSD. 

I also double checked the Apps Permissions and, with Storage being the only one, it was good to go there. 

The following screenshot reflects the error message displayed on all tries. 
[droidshows](https://user-images.githubusercontent.com/18060271/38389966-ea3f45a8-38ed-11e8-814c-e93432b82683.jpg)

**Comment by ltGuillaume** [comment]
Maybe you only read an unedited version of my post via your mail or something? I stated explicitly that I didn't do anything to allow for storage on SD cards. It's messy and annoying to implement.

And why a clean install? Trust me, you'll never have to do that (for most apps, but definitely not for DroidShows).

**Comment by ltguillaume** [comment]
Maybe you only read an unedited version of my post via your mail or something? I stated explicitly that I didn't do anything to allow for storage on SD cards. It's messy and annoying to implement and I don't know if that many people would use it anyway. Sorry for the trouble if it's because you missed the sentence I added to my post later on.

Here's a slightly edited version that will just keep you in the primary external storage folder.
[DroidShows_7.7.4.zip](https://github.com/ltGuillaume/DroidShows/files/1883803/DroidShows_7.7.4.zip)

**Comment by Ibuprophen** [comment]
Another slight confusion on my part... 

The only reason that I was looking to backup to the MicroSD is because of the slight chance that a crash incurred and the backup was safely on the MicroSD and the one you had just provided has the 3-dot option removed to change the location anywhere than at/within the default internal location. 

I'll just keep doing what I've been doing all this time... To just copy the Backup directory to the MicroSD after each/2 backups performed. 

I do appreciate your time and support for this development! :-)
