### ISSUE TITLE
Feature request: use first unseen after last seen as next episode.

### ISSUE THREAD

**Issue by Zegnat** [ltguillaume/droidshows#49]
This might seem weird in a world of binge-watching, Netflix, YouTube, and BitTorrent, but some people are still dependent on good old TV channels and their whims. This means you can’t always watch a programme starting at episode 1 of season 1.

Recently we started watching <i>Doctor Who</i> again, but we just started where the TV broadcaster was at the time: [episode 2 of season 7](http://www.imdb.com/title/tt2317659/), <i>Dinosaurs on a Spaceship</i>.

Currently DroidShows is telling me my next episode of <i>Doctor Who</i> will be 1x01. Worse still even when I go into the series it will say my next episode of Season 7 is 1x01. When I watch the next episode next week, I have to remember what season I am in because I DroidShows doesn’t focus my current season for me (#11).

I can’t imagine I am the only person alive who isn’t always able to start at 1x01.

The solution seems simple to me: instead of displaying the absolute first unseen episode of a series and season, display the first unseen episode after the last seen one.

I could go and manually mark everything as seen, but then I would lose any reliable tracking statistics. I really like how DroidShows keeps track of **when** I watched an episode.

**Comment by ltguillaume** [comment]
Hello fellow Dutchman! :-)

I feel your pain and, for now, just mark the episodes before 7x02 as seen
(as you said). The fact that they're all seen on the same date will be a
solid indication, do you can find and uncheck them later, when you'll get
your Christmas, or belated Sinterklaas, present :-)

Cheers!

**Comment by Zegnat** [comment]
> you can find and uncheck them later, when you'll get your Christmas, or belated Sinterklaas, present :-)

Tease.

I’ll keep my eyes open. Loving the application apart from this little annoyance!

**Comment by Ibuprophen** [comment]
Just a suggestion for this... 

How about a way to do the following... 

Say that you first select one of the shows... 

Within the list of seasons (or even the list of episodes within one of the seasons), being able to press and hold any of one the seasons/episodes, and having an option (within the popup menu) to select something like the following (of course with less words):

Mark this season/episode as the start for next season/episode in que. 

Something along those lines... :-) 

Just an idea/suggestion regarding this topic! 


~Ibuprophen

**Comment by ltguillaume** [comment]
@Zegnat I am almost too embarrassed to post it here, but ehm... after a whopping 15 months and a bit, I have finally implemented your request :$ Pretty sure you stopped using DroidShows by now, because you never got your 2017 Christmas present... but hey, it's here now and I wish to make amends! ;)

It will take a looooong database update to finally get this feature working, so don't be alarmed if at first start, DroidShows needs one - or several - minute(s) to catch its breath! So, careful while it's hot, it probably needs some more testing, for which I'm looking at you guys! @ibuprophen1 @CalebCDE @casperklein @fabiom

[Zze download (7.9.0beta2)](https://github.com/ltGuillaume/DroidShows/releases/download/7.8.0/DroidShows_7.9.0beta2.apk)

#### 7.9.0 beta
- [x] Function to calculate the next episode by starting from the last episode that was marked as seen (don't assume
the first unseen episode)
- [x] Include timestamp for seen mark (needed for "Mark next episode starting from the most recently watched")
- [x] Visual distinction in "Search shows" between current and archived shows
- [x] Pinned shows aren't white, but have a "pin" next to them
- [x] Open AddSerie activity when clicking the "Add show" button
- [x] Don't show toast message for automatic backups

#### 7.8.0
- [x] Prevent popup "This app was built for an older version of Android..." on >= Pie (thx @ibuprophen1)
- [x] Change synopsis language per show
- [x] Specify synopsis language when adding new shows
- [x] Long-press check box in Episode Details to change seen date
- [x] Set folder for daily backups via Backup button
- [x] Removed old restore locations
- [x] Changed date format in Restore
- [x] Don't allow for browsing above ExternalStorageDirectory
- [x] Prevent browsing outside primary external storage in Restore
- [x] Added margin for text not to overlap context menu buttons
- [x] Removed maxLines
- [x] Added Italian translation (thx @Jiack214)
- [x] Updated German translation (thx @finefin)
- [x] Updated Spanish translation (thx @CalebCDE)

**Comment by casperklein** [comment]
"Function to calculate the next episode..."
Doesn't seem to work for me. Any special doing for this? (I refreshed my entire db)
I am currently watching "south park" season 22. I went to season 10 and marked S10E05 as unwatched. After that I marked S22E08 as seen. I would expect to see S22E09 as next to watch in the tv show overview. Instead I see S10E05.

Version: 7.9.0

**Comment by Ibuprophen** [comment]
@ casperklein, ltGuillaume had posted a Beta 2 with some additional fixes on the following thread post link.

https://forum.xda-developers.com/showthread.php?p=79212410 

Hopefully it will work out for you. 

Good Luck! 


~Ibuprophen

**Comment by ltguillaume** [comment]
@casperklein It's optional, so just to be sure, did you enable the option?

@ibuprophen1 Thx, but beta1 or beta2 shouldn't be any different concerning this feature; as you can read in the changelog, I have not changed anything related to it.

**Comment by casperklein** [comment]
No, there was no option for that (afaik). However I completely removed and reinstalled beta2. Activated the option and it worked (referring to my example above: I see S22E08 as next to watch)

However, disabling the option doesn't seem to work. I still see S22E08, but would expect S10E05.

**Comment by ltguillaume** [comment]
Good point, the text should be updated right after switching. Will fix, thx.

**Comment by ltguillaume** [comment]
@casperklein https://github.com/ltGuillaume/DroidShows/releases/download/7.8.0/DroidShows_7.9.0beta3.apk fixed?

**Comment by casperklein** [comment]
Yes, fixed 👍

**Comment by ltguillaume** [comment]
Great! Thx for checking. Then I'll probably release beta3 as stable soon.

**Comment by Zegnat** [comment]
Late to the party, but this all sounds really good. Will try and put some real testing hours in this week and looking forward to it 👍

**Comment by ltguillaume** [comment]
@Zegnat Great to hear from ya, hope I have finally implemented it the way you imagined it, you know, in that other lifetime, 2017 ;-) v7.9.0 stable has been [released](https://github.com/ltGuillaume/DroidShows/releases) last night, so lucky you! :-P
