### ISSUE TITLE
Add additional category 'Watchlist' to context menu

### ISSUE THREAD

**Issue by github-userx** [ltguillaume/droidshows#63]
Currently we got:

* DroidShows
* Archive
* Log

[See Screenshot](https://i.imgur.com/SCYy1f6.png)

I would like to have an additional category called something like ***"watchlist"*** or ***"saved for later watching"*** where I can put in shows that I plan on watching but which I don't want to appear on my main page in DroidShows nor do I want them to be in the archive of shows that I finished watching.

Do you understand what I am trying yo explain? What do you think about this idea or its possibilities?

Thanks for such an awesome app!
Kind Regards!

**Comment by ltguillaume** [comment]
Hey. Sorry, I don't think I'll be adding this feature, because the inner workings of the app don't easily allow for adding more lists (which is my own fault). I've pondered on making this work somehow, but lost interest after implementing the "Pin" feature. Now, I just put "backlogged" shows (i.e. my watchlist) in the Archive and pin the shows I'm really interested in. Furthermore, because I already hide the shows I've seen completely via "Filter shows", only the backlogged shows are displayed in the Archive anyway.

**Comment by github-userx** [comment]
Thanks for the tips.
