### ISSUE TITLE
Wrong TV show poster after restoring from backup

### ISSUE THREAD

**Issue by guihkx** [ltguillaume/droidshows#72]
So I made a backup of DroidShows on my old phone yesterday so I could later restore it on this new phone I'll be using. However, after I restored the backup, I noticed the poster for the TV Show "Better Call Saul" was actually from "Game of Thrones". Then I tried updating the show to see if the poster would be updated, but it didn't. I also tried clearing the app cache, but that didn't work either. 

Is there any way (within the app) that I can update a show's poster to the correct one? By the way here's a video of that, if that helps: https://youtu.be/uuaFzWzK8e0

(I just noticed in the video that the The Walking Dead poster is gone after I restart the app as well)

**Comment by Ibuprophen** [comment]
I, personally, added the show, uninstalled the app, reinstalled the app and restored the backup. 

It restored without any issues so I, personally, couldn't duplicate this issue myself. 

Maybe you could zip up the backup files and provide it to @ltGuillaume to see if he can locate something that I can't. 

Good Luck! :-) 


~Ibuprophen

**Comment by ltguillaume** [comment]
I had the exact same thing just the other day, but with the shows Homeland an Modern Family (both had the Modern Family cover all of a sudden). The problem is probably that when covers are updated in TheTVDB, the filenames given might change into names that were previously used by replaced covers of another show. If you happen to have both those shows in your list, the cover won't be updated locally (because it already exists) and it'll show the thumbnail of that other show.

As such, I'll probably need to change the names of the local cover thumbnails to hashes of the show name or something.

For now, could you try clearing the app data and restoring the backup again?

**Comment by guihkx** [comment]
I see... Well, I tried doing that several times but it always downloads the GoT cover after I restore the backup. Here's the backup file to see if you guys can reproduce it: [removed]

**Comment by ltguillaume** [comment]
You're right, it was something else entirely. But hey, it was easier to fix this way, so here ya go: https://github.com/ltGuillaume/DroidShows/releases/tag/7.9.5

Please report back to me :)

**Comment by Ibuprophen** [comment]
I just wanted to let you know that, on my end anyway, v7.9.5 works great! :-) 

I did notice that the Poster Images (for most/all of them) are much better quality than before. 

Thank you very much! :-P 


~Ibuprophen

**Comment by guihkx** [comment]
Works for me as well. Thanks a lot!

**Comment by ltguillaume** [comment]
@guihkx Thanks for checking!

@ibuprophen1
> I did notice that the Poster Images (for most/all of them) are much better quality than before.

That's either placebo or you changed phones/ROM and now it takes more care when resampling images; I haven't changed anything there.

**Comment by Ibuprophen** [comment]
I believe that your correct! 

It must be that I've looked at the images but, not as closely as I had done when this issue was reported. :-P 

My apologies and thank you very much for your time, patience and prompt support for this development. :-D


~Ibuprophen
