### ISSUE TITLE
Add Show ->(+) blocks UI then scrolls to top

### ISSUE THREAD

**Issue by stephengeorgewest** [ltguillaume/droidshows#96]
Running 7.11.1 from f-droid.

I want to add a bunch of shows that have the word "star" in them, because i'm a nerd, so I search for "star" and press the (+) to add a show. It spins for a bit then I can scroll again to the next one. It wouldn't be too annoying except when I start adding shows after scrolling down, it resets to the top.

Would it be possible to get the "Adding show" spinner to block the single row instead of the whole list? or at least prevent the scroll to the top. I peaked into the code, and saw that it is an async task, but it only executes one async task at a time. So maybe it is not too much work?

**Comment by ltguillaume** [comment]
You're right! The reset-to-top issue should be fixed with this build (if you want to test it, unfortunately, you'll have to backup your database, uninstall the F-Droid version and reinstall this one). Otherwise you'll have to wait a few days until F-Droid picks up the new version.

As for the spinner blocking the screen, I'm gonna leave it like that to prevent issues with too many concurrent database operations.

[DroidShows_7.11.2.zip](https://github.com/ltGuillaume/DroidShows/files/5161984/DroidShows_7.11.2.zip)

**Comment by stephengeorgewest** [comment]
I just got the update via f-droid, and added some more shows. That works quite a bit better.

**Comment by ltguillaume** [comment]
I put in the full refresh because up until recently I was still using DroidShows on a device running Android 2.3.7, which has a botched handling of refreshing ListAdapters via notifyDataChanged(). Much of the peculiar code in DroidShows has to do with working around glitches in that version, to be honest 😅
